on: push
name: deploy
jobs:
  build-and-push:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image --record deployment/my-app prueba-gha=${{ github.repository }}:${{ github.sha }}
    - name: verify deployment
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      with:
        args: '"rollout status deployment/my-app"'
  ngrok-watcher:
    name: Ngrok watcher
    runs-on: ubuntu-latest
    needs: deploy-to-cluster
    steps:
    - name: Watch ngrok
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.20"
      run: echo "Hello world"
      # with:
      #   args: '"rollout status deployment/my-app"'
